tables:
 - tableName: organization
   schemas:
    - name: id
      type: text
    - name: name
      type: text
    - name: email
      type: text 
    - name: address
      type: text 
 - tableName: app_user
   schemas:
    - name: id
      type: text
    - name: username
      type: text
    - name: role
      type: text 
    - name: password
      type: text 